version: "3"

services:
  # a fully automated HTTPS server powered by Nginx, Let's Encrypt
  # see https://github.com/SteveLTN/https-portal
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - "80:80"
      - "443:443"
    # links:
    # - app:app
    environment:
      DOMAINS: >
        portal.mshin0509.com -> http://growi:3000,
        redmine.mshin0509.com -> http://redmine:3000,
        nextcloud.mshin0509.com -> http://nextcloud:80,
        onlyoffice.mshin0509.com -> http://onlyoffice:80,
        jupyterhub.mshin0509.com -> http://jupyterhub:8000,
        auth.mshin0509.com -> https://keycloak:8443
      STAGE: "production"
      FORCE_RENEW: "false"
      WEBSOCKET: "true"
      CLIENT_MAX_BODY_SIZE: 0
    restart: no
    volumes:
      - https-portal_data:/var/lib/https-portal
    networks:
      - shared_network

networks:
  shared_network:
    external: true

volumes:
  https-portal_data:
